version: '3.8'

services:
    telegram-bot:
        build:
            context: ./app
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - ./app/sessions:/app/sessions
            